### ISSUE TITLE
Getting Discord Customer does not exist

### ISSUE THREAD

**Issue by jatindhawan** [Androz2091/stripe-discord-bot#1]
Do we need to run stored procedures to add all discord users into database before using this program because I am getting this below error:

`QueryFailedError: relation "discord_customer" does not exist
    at PostgresQueryRunner.query (/Users/jatindhawan/code/stripe-discord-bot/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:211:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SelectQueryBuilder.loadRawResults (/Users/jatindhawan/code/stripe-discord-bot/node_modules/typeorm/query-builder/SelectQueryBuilder.js:2056:25)
    at async SelectQueryBuilder.executeEntitiesAndRawResults (/Users/jatindhawan/code/stripe-discord-bot/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1916:26)
    at async SelectQueryBuilder.getRawAndEntities (/Users/jatindhawan/code/stripe-discord-bot/node_modules/typeorm/query-builder/SelectQueryBuilder.js:645:29)
    at async SelectQueryBuilder.getOne (/Users/jatindhawan/code/stripe-discord-bot/node_modules/typeorm/query-builder/SelectQueryBuilder.js:672:25)
    at async run (/Users/jatindhawan/code/stripe-discord-bot/dist/slash-commands/email.js:45:26) {
  query: 'SELECT "DiscordCustomer"."id" AS "DiscordCustomer_id", "DiscordCustomer"."discordUserId" AS "DiscordCustomer_discordUserId", "DiscordCustomer"."email" AS "DiscordCustomer_email", "DiscordCustomer"."hadActiveSubscription" AS "DiscordCustomer_hadActiveSubscription", "DiscordCustomer"."firstReminderSentDayCount" AS "DiscordCustomer_firstReminderSentDayCount", "DiscordCustomer"."adminAccessEnabled" AS "DiscordCustomer_adminAccessEnabled" FROM "discord_customer" "DiscordCustomer" WHERE ("DiscordCustomer"."discordUserId" = $1) LIMIT 1',
  parameters: [ '474432994359377930' ],
  driverError: error: relation "discord_customer" does not exist
      at Parser.parseErrorMessage (/Users/jatindhawan/code/stripe-discord-bot/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/Users/jatindhawan/code/stripe-discord-bot/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/Users/jatindhawan/code/stripe-discord-bot/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/Users/jatindhawan/code/stripe-discord-bot/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at Socket.emit (node:domain:489:12)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 116,
    severity: 'ERROR',
    code: '42P01',
    detail: undefined,
    hint: undefined,
    position: '444',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '1395',
    routine: 'parserOpenTable'
  },
`

**Comment by jatindhawan** [comment]
Had to set environment to `Development` which sets synchronize to true which fixed the issue
